create table if not exists public.app_state (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  revision bigint not null default 0
);

create table if not exists public.app_state_history (
  id bigint generated by default as identity primary key,
  scope text not null,
  payload jsonb not null,
  source_revision bigint,
  created_at timestamptz not null default now()
);

create index if not exists app_state_history_scope_created_at_idx
  on public.app_state_history (scope, created_at desc);

alter table public.app_state enable row level security;
alter table public.app_state_history enable row level security;

revoke all on table public.app_state from anon, authenticated;
revoke all on table public.app_state_history from anon, authenticated;

grant select, insert, update, delete on table public.app_state to service_role;
grant select, insert, delete on table public.app_state_history to service_role;

insert into public.app_state (id, payload)
values
  ('default', '{}'::jsonb),
  ('fiscal', '{}'::jsonb)
on conflict (id) do nothing;

-- No public RLS policies are created intentionally.
-- The application writes through the signed server-to-server sync Edge Function.
-- Never expose a Supabase secret/service-role key to browser code.
